// import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import Navbar from "@/components/Demonavbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "S-mart",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				// className={inter.className}
				suppressHydrationWarning
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
